name: CI/CD for Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.mugunthragav }}
          password: ${{ secrets.dckr_pat_UrKpt7tldKVLUrViqJ78ffocoXU}}

      - name: Pull Docker image
        run: |
          docker pull mugunthragav/my-mlflow-app:latest

      - name: Deploy Docker image
        run: |
          docker run -d -p 80:80 mugunthragav/my-mlflow-app:latest
